//go:build go1.22

// Package igen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package igen

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	PublisherCCScopes publisherCCContextKey = "publisherCC.Scopes"
	TaskJWTScopes     taskJWTContextKey     = "taskJWT.Scopes"
)

// ComponentEndpoint defines model for ComponentEndpoint.
type ComponentEndpoint struct {
	Component string `json:"component"`
	URL       string `json:"url"`
}

// Error Flat error envelope returned by every non-2xx response.
type Error struct {
	// Code Machine-readable error code (stable slug).
	Code string `json:"code"`

	// Details Field-level details for validation errors.
	Details []ErrorDetail `json:"details,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Identity Git commit identity. Field names are CAPITALIZED on the wire (historical lockstep — changing them needs a coordinated runner release). KNOWN GAP: the runner's credhelper currently reads lowercase keys, so its identity-drift rewrite never fires; fix belongs runner-side (case-tolerant parse), not here.
type Identity struct {
	Email string `json:"Email"`
	Login string `json:"Login"`
	Name  string `json:"Name"`
}

// OnboardingFacts Structured facts committed as specs/onboarding/analysis.json. Facts only — never a proposed component decomposition.
type OnboardingFacts struct {
	Gaps                 []string               `json:"gaps,omitempty"`
	Languages            []string               `json:"languages,omitempty"`
	Ref                  string                 `json:"ref"`
	SourceRepo           string                 `json:"sourceRepo"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// RefreshResponse Fresh GitHub token + commit identity for the execution.
type RefreshResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Identity Git commit identity. Field names are CAPITALIZED on the wire (historical lockstep — changing them needs a coordinated runner release). KNOWN GAP: the runner's credhelper currently reads lowercase keys, so its identity-drift rewrite never fires; fix belongs runner-side (case-tolerant parse), not here.
	Identity Identity `json:"identity"`
	TaskID   string   `json:"taskId"`
	Token    string   `json:"token"`
}

// TestCredential Test login credentials for a validation run. Generated as igen.TestCredential (no x-go-type); the edge's internal handler projects the delivery domain's own struct onto this wire shape.
type TestCredential struct {
	Mock     bool   `json:"mock"`
	Note     string `json:"note,omitempty"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// TestCredentialRequest Optional hints for a runner test-credential request.
type TestCredentialRequest struct {
	Purpose  string `json:"purpose,omitempty"`
	Role     string `json:"role,omitempty"`
	Username string `json:"username,omitempty"`
}

// ValidationContextResponse Deployed endpoints + criteria path for a validation run. Generated as igen.ValidationContextResponse (no x-go-type) — igen must stay a leaf, so the edge's internal handler projects the delivery domain's own struct onto this wire shape (the same decoupling as RefreshResponse).
type ValidationContextResponse struct {
	CriteriaPath string              `json:"criteriaPath"`
	Endpoints    []ComponentEndpoint `json:"endpoints"`
}

// publisherCCContextKey is the context key for publisherCC security scheme
type publisherCCContextKey string

// taskJWTContextKey is the context key for taskJWT security scheme
type taskJWTContextKey string

// RunnerOnboardingFactsJSONRequestBody defines body for RunnerOnboardingFacts for application/json ContentType.
type RunnerOnboardingFactsJSONRequestBody = OnboardingFacts

// RunnerValidationCredentialsJSONRequestBody defines body for RunnerValidationCredentials for application/json ContentType.
type RunnerValidationCredentialsJSONRequestBody = TestCredentialRequest

// Getter for additional properties for OnboardingFacts. Returns the specified
// element and whether it was found
func (a OnboardingFacts) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OnboardingFacts
func (a *OnboardingFacts) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OnboardingFacts to handle AdditionalProperties
func (a *OnboardingFacts) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["gaps"]; found {
		err = json.Unmarshal(raw, &a.Gaps)
		if err != nil {
			return fmt.Errorf("error reading 'gaps': %w", err)
		}
		delete(object, "gaps")
	}

	if raw, found := object["languages"]; found {
		err = json.Unmarshal(raw, &a.Languages)
		if err != nil {
			return fmt.Errorf("error reading 'languages': %w", err)
		}
		delete(object, "languages")
	}

	if raw, found := object["ref"]; found {
		err = json.Unmarshal(raw, &a.Ref)
		if err != nil {
			return fmt.Errorf("error reading 'ref': %w", err)
		}
		delete(object, "ref")
	}

	if raw, found := object["sourceRepo"]; found {
		err = json.Unmarshal(raw, &a.SourceRepo)
		if err != nil {
			return fmt.Errorf("error reading 'sourceRepo': %w", err)
		}
		delete(object, "sourceRepo")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OnboardingFacts to handle AdditionalProperties
func (a OnboardingFacts) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Gaps != nil {
		object["gaps"], err = json.Marshal(a.Gaps)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gaps': %w", err)
		}
	}

	if a.Languages != nil {
		object["languages"], err = json.Marshal(a.Languages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'languages': %w", err)
		}
	}

	object["ref"], err = json.Marshal(a.Ref)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ref': %w", err)
	}

	object["sourceRepo"], err = json.Marshal(a.SourceRepo)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'sourceRepo': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Refresh an execution's git credentials (runner callback)
	// (POST /executions/{executionId}/credentials/refresh)
	RunnerRefreshCredentials(w http.ResponseWriter, r *http.Request, executionID string)
	// Post structured onboarding analysis facts (runner callback)
	// (POST /onboarding/{executionId}/facts)
	RunnerOnboardingFacts(w http.ResponseWriter, r *http.Request, executionID string)
	// Fetch a validation run's deployed endpoints (runner callback)
	// (GET /validation/{cycleId}/context)
	RunnerValidationContext(w http.ResponseWriter, r *http.Request, cycleID string)
	// Request test credentials for a validation run (runner callback)
	// (POST /validation/{cycleId}/test-credentials)
	RunnerValidationCredentials(w http.ResponseWriter, r *http.Request, cycleID string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RunnerRefreshCredentials operation middleware
func (siw *ServerInterfaceWrapper) RunnerRefreshCredentials(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "executionId" -------------
	var executionID string

	err = runtime.BindStyledParameterWithOptions("simple", "executionId", r.PathValue("executionId"), &executionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TaskJWTScopes, []string{})

	ctx = context.WithValue(ctx, PublisherCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerRefreshCredentials(w, r, executionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunnerOnboardingFacts operation middleware
func (siw *ServerInterfaceWrapper) RunnerOnboardingFacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "executionId" -------------
	var executionID string

	err = runtime.BindStyledParameterWithOptions("simple", "executionId", r.PathValue("executionId"), &executionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TaskJWTScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerOnboardingFacts(w, r, executionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunnerValidationContext operation middleware
func (siw *ServerInterfaceWrapper) RunnerValidationContext(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cycleId" -------------
	var cycleID string

	err = runtime.BindStyledParameterWithOptions("simple", "cycleId", r.PathValue("cycleId"), &cycleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cycleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TaskJWTScopes, []string{})

	ctx = context.WithValue(ctx, PublisherCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerValidationContext(w, r, cycleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunnerValidationCredentials operation middleware
func (siw *ServerInterfaceWrapper) RunnerValidationCredentials(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "cycleId" -------------
	var cycleID string

	err = runtime.BindStyledParameterWithOptions("simple", "cycleId", r.PathValue("cycleId"), &cycleID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cycleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TaskJWTScopes, []string{})

	ctx = context.WithValue(ctx, PublisherCCScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunnerValidationCredentials(w, r, cycleID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/executions/{executionId}/credentials/refresh", wrapper.RunnerRefreshCredentials)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/onboarding/{executionId}/facts", wrapper.RunnerOnboardingFacts)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/validation/{cycleId}/context", wrapper.RunnerValidationContext)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/validation/{cycleId}/test-credentials", wrapper.RunnerValidationCredentials)

	return m
}

type RunnerRefreshCredentialsRequestObject struct {
	ExecutionID string `json:"executionId"`
}

type RunnerRefreshCredentialsResponseObject interface {
	VisitRunnerRefreshCredentialsResponse(w http.ResponseWriter) error
}

type RunnerRefreshCredentials200JSONResponse RefreshResponse

func (response RunnerRefreshCredentials200JSONResponse) VisitRunnerRefreshCredentialsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerRefreshCredentialsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RunnerRefreshCredentialsdefaultJSONResponse) VisitRunnerRefreshCredentialsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerOnboardingFactsRequestObject struct {
	ExecutionID string `json:"executionId"`
	Body        *RunnerOnboardingFactsJSONRequestBody
}

type RunnerOnboardingFactsResponseObject interface {
	VisitRunnerOnboardingFactsResponse(w http.ResponseWriter) error
}

type RunnerOnboardingFacts204Response struct {
}

func (response RunnerOnboardingFacts204Response) VisitRunnerOnboardingFactsResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RunnerOnboardingFactsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RunnerOnboardingFactsdefaultJSONResponse) VisitRunnerOnboardingFactsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationContextRequestObject struct {
	CycleID string `json:"cycleId"`
}

type RunnerValidationContextResponseObject interface {
	VisitRunnerValidationContextResponse(w http.ResponseWriter) error
}

type RunnerValidationContext200JSONResponse ValidationContextResponse

func (response RunnerValidationContext200JSONResponse) VisitRunnerValidationContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationContextdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RunnerValidationContextdefaultJSONResponse) VisitRunnerValidationContextResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationCredentialsRequestObject struct {
	CycleID string `json:"cycleId"`
	Body    *RunnerValidationCredentialsJSONRequestBody
}

type RunnerValidationCredentialsResponseObject interface {
	VisitRunnerValidationCredentialsResponse(w http.ResponseWriter) error
}

type RunnerValidationCredentials200JSONResponse TestCredential

func (response RunnerValidationCredentials200JSONResponse) VisitRunnerValidationCredentialsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunnerValidationCredentialsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RunnerValidationCredentialsdefaultJSONResponse) VisitRunnerValidationCredentialsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Refresh an execution's git credentials (runner callback)
	// (POST /executions/{executionId}/credentials/refresh)
	RunnerRefreshCredentials(ctx context.Context, request RunnerRefreshCredentialsRequestObject) (RunnerRefreshCredentialsResponseObject, error)
	// Post structured onboarding analysis facts (runner callback)
	// (POST /onboarding/{executionId}/facts)
	RunnerOnboardingFacts(ctx context.Context, request RunnerOnboardingFactsRequestObject) (RunnerOnboardingFactsResponseObject, error)
	// Fetch a validation run's deployed endpoints (runner callback)
	// (GET /validation/{cycleId}/context)
	RunnerValidationContext(ctx context.Context, request RunnerValidationContextRequestObject) (RunnerValidationContextResponseObject, error)
	// Request test credentials for a validation run (runner callback)
	// (POST /validation/{cycleId}/test-credentials)
	RunnerValidationCredentials(ctx context.Context, request RunnerValidationCredentialsRequestObject) (RunnerValidationCredentialsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RunnerRefreshCredentials operation middleware
func (sh *strictHandler) RunnerRefreshCredentials(w http.ResponseWriter, r *http.Request, executionID string) {
	var request RunnerRefreshCredentialsRequestObject

	request.ExecutionID = executionID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunnerRefreshCredentials(ctx, request.(RunnerRefreshCredentialsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunnerRefreshCredentials")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunnerRefreshCredentialsResponseObject); ok {
		if err := validResponse.VisitRunnerRefreshCredentialsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunnerOnboardingFacts operation middleware
func (sh *strictHandler) RunnerOnboardingFacts(w http.ResponseWriter, r *http.Request, executionID string) {
	var request RunnerOnboardingFactsRequestObject

	request.ExecutionID = executionID

	var body RunnerOnboardingFactsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunnerOnboardingFacts(ctx, request.(RunnerOnboardingFactsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunnerOnboardingFacts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunnerOnboardingFactsResponseObject); ok {
		if err := validResponse.VisitRunnerOnboardingFactsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunnerValidationContext operation middleware
func (sh *strictHandler) RunnerValidationContext(w http.ResponseWriter, r *http.Request, cycleID string) {
	var request RunnerValidationContextRequestObject

	request.CycleID = cycleID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunnerValidationContext(ctx, request.(RunnerValidationContextRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunnerValidationContext")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunnerValidationContextResponseObject); ok {
		if err := validResponse.VisitRunnerValidationContextResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunnerValidationCredentials operation middleware
func (sh *strictHandler) RunnerValidationCredentials(w http.ResponseWriter, r *http.Request, cycleID string) {
	var request RunnerValidationCredentialsRequestObject

	request.CycleID = cycleID

	var body RunnerValidationCredentialsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunnerValidationCredentials(ctx, request.(RunnerValidationCredentialsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunnerValidationCredentials")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunnerValidationCredentialsResponseObject); ok {
		if err := validResponse.VisitRunnerValidationCredentialsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
